name: SQL Query Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  instances: localhost\SQLEXPRESS
  sql_scripts_folder: "./sql_scripts"
  db_list_doc: "./sql_db.txt"
  
jobs:
  SQL_Query:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: SQL Query Test
        run: |
              $instance = "$env:instances"
              Write-Output "Adding tables to $instance"
              $sqlScriptsFolderPath = "$env:sql_scripts_folder"
              $sqlFiles = Get-ChildItem -Path $sqlScriptsFolderPath -Filter *.sql
              $DB_List_loc =  "$env:db_list_doc"
              $DB_Names = "JordansDB"

              $array = $DB_Names -split " "
              Set-Content -Path $DB_List_loc -Value $array
              $DBs = Get-Content $DB_List_loc

              try {
               Write-Output "Executing script on Environment "
               foreach ($DB in $DBs) {
                 Write-Host "Connecting to SQL Server Database: $DB"
                 # Loop through each SQL file in the folder
               foreach ($sqlFile in $sqlFiles) {   
                   $sqlFilePath = $sqlFile.FullName
                   Write-Output "Executing script: $sqlFilePath"
                   sqlcmd -S $instance -d $DB -i $sqlFilePath
                  }
                 }
               }
               catch {
                Write-Output "Error executing script"
               }
          
        shell: powershell
